export const TOOGLE_INFO_MODAL = "TOOGLE_INFO_MODAL";

/* FETCHING */
export const FETCHING_SECTORS_PENDING = "FETCHING_SECTORS_PENDING";
export const FETCHING_SECTORS_SUCCESS = "FETCHING_SECTORS_SUCCESS";
export const FETCHING_SECTORS_ERROR = "FETCHING_SECTORS_ERROR";
