export const APP_CONFIG = "APP_CONFIG";
export const APP_DATA = "APP_DATA";

export const PAGE_IS_LOADING = "PAGE_IS_LOADING";
export const TOOGLE_INFO_MODAL = "TOOGLE_INFO_MODAL";
export const MINIMIZED = "SHOW_HIDE_COMPONENT";

/* User location*/
export const FETCHING_USER_LOCATION_PENDINNG = "FETCHING_USER_LOCATION_PENDINNG";
export const FETCHING_USER_LOCATION_SUCCESS = "FETCHING_USER_LOCATION_SUCCESS";
export const FETCHING_USER_LOCATION_ERROR = "FETCHING_USER_LOCATION_ERROR";

/* FETCHING */
export const FETCHING_PENDING = "FETCHING_PENDING";
export const FETCHING_SUCCESS = "FETCHING_SUCCESS";
export const FETCHING_ERROR = "FETCHING_ERROR";
